PrimeDAO/contracts

- .circleci/config.yml
- test/farm-factory.js
- test/staking-rewards.js
- test/staking-simulation-1-month-happypath.js
- test/staking-simulation-1-week-happypath.js
- truffle-config.js
Closes https://github.com/PrimeDAO/contracts/issues/10
> Add: Circleci project setup

- README.md
Closes https://github.com/PrimeDAO/contracts/issues/12
> Stylize README

- contracts/schemes/FarmFactory.sol
- test/farm-factory.js
- test/helpers/index.js
Closes https://github.com/PrimeDAO/contracts/issues/4
> Add farm struct

- contracts/incentives/StakingRewards.sol
- contracts/schemes/FarmFactory.sol
- contracts/utils/CloneFactory.sol
- contracts/utils/interfaces/IRewardDistributionRecipient.sol
- package-lock.json
- test/farm-factory.js
- test/helpers/setup.js
- test/staking-rewards.js
Added clone factory to the clone factory.
> added clone factory

- contracts/utils/interfaces/IRewardDistributionRecipient.sol
- test/staking-rewards.js
Closes https://github.com/PrimeDAO/contracts/issues/39
> Tests fixed + I noticed that I must've messed up a contract somewhere

- contracts/incentives/StakingRewards.sol
Closes https://github.com/PrimeDAO/contracts/issues/52
> fix duration

- contracts/incentives/StakingRewards.sol
> isActive function added to StakingRewards

- contracts/incentives/FarmFactory.sol
- contracts/seed/SeedFactory.sol
- test/balancer-multicall.js
- test/helpers/index.js
- test/helpers/setup.js
- test/seed-factory-multicall.js
Closes https://github.com/PrimeDAO/contracts/issues/62
> Feature: create seed with generic scheme multicall

- contracts/seed/Seed.sol
- test/seed.js
> There can be only one(occurence of data field in the structure)

- contracts/seed/Seed.sol
> dead code and some unneeded params are removed

- contracts/seed/Seed.sol
> SafeMath overload protection

- contracts/seed/Seed.sol
> calculations fix

- contracts/seed/Seed.sol
- test/seed.js
> Removed not used variables from lock

- config.json
- contracts/incentives/FarmFactory.sol
- contracts/incentives/StakingRewards.sol
- farmconfig.json
- scripts/kovan/createPool.js
- scripts/kovan/innitRewards.js
- test/staking-rewards.js
- test/staking-simulation-1-month-happypath.js
- test/staking-simulation-1-week-happypath.js
Closes https://github.com/PrimeDAO/contracts/issues/94
> 94 deploy to kovan

- contracts/incentives/FarmFactory.sol
> renewed amount

- contracts/incentives/FarmFactory.sol
Closes https://github.com/PrimeDAO/contracts/issues/103
> Add: notifyRewardAmount to FarmFactory

- contracts/seed/Seed.sol
For Issue #84  
Removed checked modifier as the admin can un-whitelist the user, after the user have funded it. This prevents user from retrieving funding amount.
added require() to check fundingAmount>0 so that even if the Seed is whitelisted or not, you can only retrieve only if you have funded it.
> For Issue #84 @ Seed.sol:220 retrieveFundingTokens()

- contracts/seed/Seed.sol
- contracts/seed/SeedFactory.sol
- test/helpers/index.js
- test/seed-factory-multicall.js
- test/seed-factory.js
- test/seed.js
Resolves #93 
Resolves #89 
Renamed cap and successMinimum to hardCap and softCap respectively
Corrected calculations for ```seedToken``` amount at ```SeedFactory.sol```.
> For Issue #93 - Renamed cap and successMinimum to hardCap and softCap respectively and corrected calculation for seedToken amount.

- contracts/Migrations.sol
- contracts/PrimeToken.sol
- contracts/RepRedeemer.sol
- contracts/incentives/FarmFactory.sol
- contracts/incentives/StakingRewards.sol
- contracts/schemes/BalancerProxy.sol
- contracts/schemes/GenericSchemeMulticall.sol
- contracts/schemes/SchemeConstraints.sol
- contracts/utils/CloneFactory.sol
- contracts/utils/PriceOracle.sol
- contracts/utils/interfaces/IRewardDistributionRecipient.sol
- contracts/utils/test/ERC20Mock.sol
Fixed solidity version and changed tabs to spaces
> Solidity version fix

- contracts/utils/interfaces/IRewardDistributionRecipient.sol
- test/staking-rewards.js
Closes https://github.com/PrimeDAO/contracts/issues/121
> 121 Fix `setRewardDistribution`

- contracts/incentives/FarmFactory.sol
> fix indent & add spaces

- test/staking-rewards.js
Closes #132 
Added test for stakingRewards.isActive().
> added test stakingRewards.isActive

- test/seed.js
Closes #133 
Added tests for seed.calculateClaim() and seed.totalClaimed
> Issue #133 - Improve Seed.sol test coverage

- contracts/seed/Seed.sol
- package-lock.json
- test/seed.js
Closes https://github.com/PrimeDAO/contracts/issues/137
Closes https://github.com/PrimeDAO/contracts/issues/138
> 137 fix modifier naming 

- contracts/seed/Seed.sol
- contracts/seed/SeedFactory.sol
Improved function documentations for Seed Module.
> Docs Improvement for Seed Module

- contracts/seed/Seed.sol
- test/seed.js
Things in this PR:-
1) Resolves #154 
2) Improved modifiers as mentioned in #148
> Improvement: Improved Modifier

- contracts/seed/SeedFactory.sol
- test/helpers/index.js
- test/helpers/setup.js
- test/seed-factory-multicall.js
- test/seed-factory.js
Shifting SeedFactory contract from using DaoStack's Avatar to OpenZeppelin's Ownable.
> Migrating SeedFactory to use Ownable

- contracts/seed/SeedFactory.sol
- test/helpers/index.js
- test/seed-factory-multicall.js
- test/seed-factory.js
Please ignore the branch name. It should be ```seed-factory-ownable```.
> Added require check for _mastercopy != address(0)
